R/standard_figures.R
Added cumulative_enrolled and enrollment_by_site for NSAID, fixed date formatting in cumulative figures
=> Added cumulative_enrolled, and enrollment_by_site

R/closed_tables.R
Correcting alignment for SAE output, discontinuation and protocol dev…
=> Correcting alignment for SAE output, discontinuation and protocol deviation 

R/closed_tables.R, man/closed_injury_ankle_plateau_characteristics.Rd
<!-- Renamed construct item(schatzker_type to injury_classification_plat_schatzker)
=> Changed named of the construct item(schatzker_type) to injury_classification_plat_schatzker

R/standard_figures.R
fixed a bug in cumulative_enrollment_goals calling a df that didn't exist yet
=> bug fix for cumulative enrollment goals

R/standard_tables.R
Adding footnotes and percentages to the rest of the expected visit table by each site
=> Adding footnotes and percentages to the rest of the expected visit table by each site

R/standard_tables.R
Added percentage for top_n_reasons of refusal
=> Added percentage for top_n_reasons of refusal

R/standard_tables.R, man/enrollment_by_site_var_disc_tobra_sextant.Rd
Added argument for days and title to incorporate nsaids "Last 7 days"
=> Added argument for days and title to incorporate nsaids "Last 7 days"

R/standard_tables.R
fixed several bugs in ineligibility_reasons, causing it to overwrite reasons that were a part of the top 5, as well as displaying an incorrect header name
=> ineligibility reasons update

R/standard_tables.R
Fixed add_footnote in enrollment by site function
=> Fixed add_footnote in enrollment by site function

R/standard_tables.R
Fixed an error with main paper patient characteristic function
=> Fixed an error with main paper patient characteristic function

R/standard_tables.R
Adding 'Total' for refusal reasons by each site for Sextant
=> Adding 'Total' for refusal reasons by each site for Sextant

R/standard_tables.R
Removing padding = '2L' from all the functions in standard_tables file
=> Removing padding = '2L'

R/standard_figures.R, man/consort_diagram.Rd
final updates for consort diagram with safety set and keyword argument
=> consort_diagram for final updates

R/standard_tables.R
made it when certain sums in summarize statements were being calculated, it wasn't using multiple dfs with cascades filters, they now filter within the summarize statement
=> Fixed enrollment_by_site_last_days_var_disc aka Number of Subjects Screened, Eligible, Enrolled, and Not Enrolled (Variable Discontinued)

R/standard_tables.R
… in ineligibility reasons table
Adding total to the followup tables and correcting number of screened in ineligibility reasons table
=> Adding total to the followup tables and correcting number of screened in ineligibility reasons table

R/standard_tables.R
updated total rows for all four tobra followup tables, last of total rows updates
=> final pull request based on notes from last visualization review

R/closed_tables.R, R/standard_figures.R, R/standard_tables.R
Added more Complication categories for the closed report
=> Added more Complication categories for the closed report

R/standard_tables.R
Fixed issue in Table 2.1 Status of IRB Approvals and Certification by Site where sites weren't sorting properly
Fixed issue in all followup tables where expected was defined incorrectly, fixed issue in 6mo follow up where column names weren't applied correctly
=> bug fixes and edits for tobra visualizations

R/gray_tables.R, R/standard_figures.R
Bug fix for adherence table and consort diagram
=> Bug fix for adherence table and consort diagram

R/standard_tables.R, man/expected_and_followup_visit_sextant.Rd
expected and visit status for tobra, only looking at CFU (crf09) the reason this function is written the way it was is because I was writing this function originally for every form, which was vey contrived and confusing. I made edits to that original code to produce this.
=> expected and visit status for tobra

R/closed_tables.R
Fixed errors in demographics closed function
=> Fixed errors in demographics closed function 

R/closed_tables.R, man/closed_expected_and_followup_visit.Rd, man/closed_ih_and_dc_crossover_monitoring_by_site.Rd
added footnotes arg to some stacked functions that were made for nsaid before the footnotes change to how we make stacked functions
=> added footnotes arg to some stacked functions

R/closed_tables.R
Bug fix for column names in SAE zipped construct
=> Bug fix for column names in SAE zipped construct

R/closed_tables.R
fixed return statement in overall complications function for tobra closed, fixed key for fracture characteristics
=> fixed return statement to kable visual

R/closed_tables.R
fixed closed baseline characteristics by excluding category column
=> fixed closed baseline characteristics

R/closed_tables.R
changed string detect for proper nrow in indentation, now properly indented. Also confirmed using the same code as open version
=> closed fracture characteristics indentation issue

R/standard_tables.R
used same code as tobra for percents in sextant fu
=> used same code as tobra for percents in sextant fu

R/closed_tables.R
Updating stability confirmation for expected and followup visit Sextant
=> Updating stability confirmation for expected and followup visit Sextant

R/standard_tables.R
overall  fu for all studies changed df unzipping seps
=> changed seps in accordance with new long file seps

R/standard_figures.R
Made changes for the width of the histogram
=> Made changes for the width of the histogram

R/closed_tables.R
added footnotes to closed overall
=> added footnotes to closed overall

R/standard_tables.R, man/closed_expected_and_followup_visit_overall.Rd
Bug fix for Sextant wide tables by site for 6 months followup status
=> Bug fix for Sextant wide tables by site for 6 months followup status

R/standard_tables.R, man/ankle_and_plateau_x_ray_and_measurement_status.Rd
Bug fix for ankle and palteau x-ray measurement status
=> Bug fix for ankle and palteau x-ray measurement status

R/standard_figures.R, man/consort_diagram.Rd
Updating consort diagram function for Sextant
=> Updating consort diagram function for Sextant

R/closed_tables.R, man/closed_dssi_reported_adjudicated.Rd
Renamed 'infection' string to 'dssi' to be specific
=> Renamed 'infection' string to 'dssi' to be specific

R/standard_tables.R, man/not_enrolled_for_other_reasons.Rd
Fixing main paper visualization for preinjury major activity
=> Fixing main paper visualization for preinjury major activity

R/standard_figures.R
Fixed late_ineligible string and var in consort diagram
=> Fixed late_ineligible string and var in consort diagram

R/standard_figures.R, R/standard_tables.R, man/enrollment_by_site.Rd, man/followup_completion_time_stats.Rd
=> added followup stats function

R/closed_tables.R, R/standard_tables.R
=> updated new form status nomenclature

R/standard_tables.R, man/enrollment_by_site_last_days_var_disc.Rd
updates enrollment by site variable discontinued function for tobra and sextant such that 'days' argument can now handle vector of days, and new argument 'average' which toggles the average per week column.
=> enrollment by site var disc changes for tobra/sextant

R/closed_tables.R, R/standard_tables.R
added horizontal support for all forms all times
=> all forms all times horizontal

R/closed_tables.R, man/closed_followup_form_all_timepoints_by_site.Rd, man/closed_followup_forms_all_timepoints.Rd, man/closed_followup_forms_at_timepoint_by_site.Rd, man/followup_forms_all_timepoints.Rd
=> added footnote arg to closed vis

R/standard_tables.R
Function now format_count_percent the last days columns in the correct order such that the total row can still be calculated correctly. Function now has cumulative_data argument set default to true, but when set to false hides all of the cumulative data columns.
=> bug fixes for enrollment by site var disc for tobra sextant + cumulative data arg

R/closed_tables.R, man/enrollment_by_site_last_days_var_disc.Rd
Bug fix for closed injury charactetistics for weight bearing
=> Bug fix for closed injury charactetistics for weight bearing

R/closed_tables.R
fixed the error with replacing NAs in complications by severity and relatedness for WBS
=> fixed the error with replacing NAs in complications by severity and relatedness for WBS

R/standard_tables.R, man/ineligibility_by_reasons.Rd
…d pre_screened
Modify ineligibility reasons to accomodate pre_ineligility reasons and pre_screened
=> Modify ineligibility reasons to accomodate pre_ineligility reasons and pre_screened

R/standard_tables.R
Bug fix for ineligibility_reasons and not_completed_Sae_pd table
=> Bug fix for ineligibility_reasons and not_completed_Sae_pd table

R/standard_figures.R
Fixed issue where days where alphabetically sorted insted of numerically sorted. I get that the double type change looks weird, but for some reason as.numeric() can't be called by itself.
=> fixed cumulative enrollment aesthetic issue

R/closed_tables.R
not sure why but the key changed, I havent made any changes since the last pull request
=> key change for fracture characteristics

R/closed_tables.R
=> added na treatment arm screened data

R/closed_tables.R
=> closed complete data

R/standard_figures.R, man/consort_diagram.Rd, man/consort_diagram_no_definitive_event.Rd, man/dsmb_consort_diagram.Rd, man/dsmb_consort_diagram_pre_no_def.Rd, man/dsmb_consort_diagram_pre_no_def_shifted_consent.Rd, man/dsmb_consort_diagram_pre_shifted_consent.Rd, man/dsmb_nsaid_consort_diagram.Rd
incomplete, and incomplete_final_followup added in accordance with consort diagrams that are applicable. Added in second line of box.
=> incomplete final followup added to all consort diagrama that use missing final followup

R/standard_tables.R
Notably, this does not format the other reasons column, because the numerator and denominator don't make sense if there are multiple reasons per study_id
=> added format_count_percent to inelig visualization

R/standard_tables.R
Filtering protocol deviations for "consented" instead of "enrolled"
=> Filtering protocol deviations for "consented" instead of "enrolled"

R/standard_tables.R, man/ineligibility_by_reasons.Rd, man/not_complete_sae_deviation_by_type.Rd, man/not_complete_sae_deviation_by_type_auto_categories.Rd
=> Fixed a few descriptions

R/closed_tables.R, R/standard_tables.R, man/closed_appendix_A_SAEs.Rd, man/closed_appendix_D_protocol_deviation.Rd, man/followup_form_at_timepoint_by_site.Rd
=> update for example running

R/closed_tables.R
updated closed fracture characteristics to join, such that it maintains the output levels, handles 0s, and has another condition for indentation.
=> Fixed 6.1 for tuacs

R/closed_tables.R, R/gray_tables.R, R/standard_figures.R, R/standard_tables.R, man/adherence_by_site.Rd, man/baseline_characteristics_percent_nm.Rd, man/closed_adherence_sextant.Rd, man/closed_appendix_B_deaths.Rd, man/closed_baseline_characteristics_percent.Rd, man/closed_characteristics_treatment.Rd, man/closed_dssi_reported_adjudicated.Rd, man/closed_enrollment_status_by_site_var_discontinued.Rd, man/closed_followup_form_at_timepoint_by_site.Rd, man/closed_fracture_characteristics.Rd, man/closed_ih_and_dc_crossover_monitoring_by_site_cutoff_date.Rd, man/closed_not_complete_sae_deviation_by_type.Rd, man/cumulative_enrolled_los.Rd, man/cumulative_percentage_plateau_injuries.Rd, man/dsmb_consort_diagram_pre_no_def.Rd, man/dsmb_nsaid_consort_diagram.Rd, man/enrollment_by_site.Rd, man/enrollment_status_by_site_var_discontinued.Rd, man/followup_form_all_timepoints_by_site.Rd, man/followup_form_at_timepoint_by_site.Rd, man/followup_forms_at_timepoint_by_site.Rd, man/ih_and_dc_crossover_monitoring_by_site.Rd, man/ineligibility_reasons_info.Rd, man/nonunion_surgery_outcome.Rd, man/not_enrolled_for_other_reasons.Rd, man/wbs_main_paper_patient_characteristics.Rd
=> dummy data update part 1

R/closed_tables.R, R/gray_tables.R, R/standard_figures.R, R/standard_tables.R, man/amputations_and_gustilo_injury_characteristics.Rd
=> dummy data tweak

R/closed_tables.R, R/gray_tables.R, R/standard_figures.R, R/standard_tables.R
Completed and tested code for examples for functions assigned to me. all completed with if_needed_generate_example_data()
=> Examples in sheet done

R/closed_tables.R
=> justifiable stability updates

R/closed_tables.R, man/adjudications_and_discontinuations_by_type.Rd, man/baseline_characteristics_percent.Rd, man/characteristics_treatment.Rd, man/closed_appendix_A_SAEs.Rd, man/closed_appendix_B_deaths.Rd, man/closed_certification_date_data.Rd, man/closed_complications_overall.Rd, man/closed_enrollment_status_by_site.Rd, man/closed_followup_form_all_timepoints_by_site.Rd, man/closed_ih_and_dc_crossover_monitoring_by_site.Rd, man/closed_injury_characteristics_by_alternate_constructs.Rd, man/complications_by_severity_relatedness.Rd, man/cumulative_enrolled.Rd, man/cumulative_percentage_ankle_injuries.Rd, man/dsmb_consort_diagram.Rd, man/dsmb_consort_diagram_pre_shifted_consent.Rd, man/enrollment_by_injury_and_site.Rd, man/enrollment_status_by_site.Rd, man/followup_completion_time_stats.Rd, man/followup_forms_all_timepoints.Rd, man/ineligibility_by_reasons.Rd, man/injury_characteristics_by_alternate_constructs.Rd, man/not_complete_sae_deviation_by_type.Rd, man/not_complete_sae_deviation_by_type_auto_categories.Rd, man/refusal_reasons_by_site.Rd, man/wbs_main_paper_injury_characteristics.Rd
=> build and bugfix

R/standard_figures.R, R/standard_tables.R
=> minor changes

R/closed_tables.R, R/standard_tables.R
…istics
Fixing error with the wbs main paper visualization- patient characteristics
=> Fixing error with the wbs main paper visualization- patient characteristics

R/closed_tables.R
=> updated stability for all vis except followup form/s at/all timepoints

R/closed_tables.R, man/closed_appendix_C_not_expected_not_completed.Rd
Fixing closed baseline characteristics nm
=> Fixing closed baseline characteristics nm

R/closed_tables.R, man/closed_appendix_C_not_expected_not_completed.Rd, man/closed_dssi_reported_adjudicated.Rd
=> dssi visualization update

R/closed_tables.R, R/standard_tables.R
=> vis bugfixes

R/closed_tables.R
=> Bugfix collection

R/standard_figures.R, R/standard_tables.R, man/complications_by_severity_relatedness.Rd, man/consort_diagram_no_definitive_event.Rd, man/cumulative_percentage_ankle_injuries.Rd, man/cumulative_percentage_plateau_injuries.Rd, man/dsmb_consort_diagram.Rd, man/dsmb_consort_diagram_pre_no_def.Rd, man/enrollment_by_site.Rd, man/enrollment_by_site_last_days_var_disc.Rd, man/enrollment_status_by_site.Rd, man/enrollment_status_by_site_var_discontinued.Rd, man/followup_form_all_timepoints_by_site.Rd, man/ineligibility_by_reasons.Rd, man/ineligibility_reasons_info.Rd, man/not_complete_sae_deviation_by_type_auto_categories.Rd, man/not_enrolled_reason.Rd, man/outcome_by_id.Rd, man/outcome_by_site.Rd
=> doc updates

R/closed_tables.R
=> stability update

R/standard_figures.R, man/dsmb_consort_diagram_pre_shifted_consent.Rd
added keyword arguments in accordance with peg requests alongside script updates to the weekly and the dsmb
=> peg consort diagram updated

R/standard_tables.R
=> title update

R/standard_tables.R, man/monitoring_required.Rd
=> Monitoring Required Update

R/standard_tables.R
=> not_enrolled_reason

R/closed_tables.R, R/gray_tables.R, man/characteristics_treatment.Rd, man/closed_characteristics_treatment.Rd
=> updated construct names for pil and plat incisions, updated key for closed characteristics_treatment

R/closed_tables.R
=> stab update

R/closed_tables.R
=> closed_fracture_characteristics bugfix
